import pb from '@/lib/pocketbase/client'
import type { Agent } from '@/types'

const mockAgents: Agent[] = [
  {
    id: 'a1',
    name: 'Ana Silva',
    email: 'ana@emp.com',
    team_id: 't1',
    avatar: '',
    status: 'active',
    role: 'lead',
    total_conversations: 245,
    conversion_rate: 32.5,
    avg_response_time: 45,
    satisfaction_score: 4.7,
    created: '',
    updated: '',
    expand: { team_id: { id: 't1', name: 'Vendas Online' } },
  },
  {
    id: 'a2',
    name: 'Bruno Costa',
    email: 'bruno@emp.com',
    team_id: 't1',
    avatar: '',
    status: 'active',
    role: 'senior',
    total_conversations: 198,
    conversion_rate: 28.3,
    avg_response_time: 52,
    satisfaction_score: 4.5,
    created: '',
    updated: '',
    expand: { team_id: { id: 't1', name: 'Vendas Online' } },
  },
  {
    id: 'a3',
    name: 'Carla Mendes',
    email: 'carla@emp.com',
    team_id: 't1',
    avatar: '',
    status: 'active',
    role: 'agent',
    total_conversations: 156,
    conversion_rate: 22.1,
    avg_response_time: 68,
    satisfaction_score: 4.2,
    created: '',
    updated: '',
    expand: { team_id: { id: 't1', name: 'Vendas Online' } },
  },
  {
    id: 'a4',
    name: 'Diego Santos',
    email: 'diego@emp.com',
    team_id: 't2',
    avatar: '',
    status: 'active',
    role: 'senior',
    total_conversations: 187,
    conversion_rate: 35.2,
    avg_response_time: 38,
    satisfaction_score: 4.8,
    created: '',
    updated: '',
    expand: { team_id: { id: 't2', name: 'Suporte Premium' } },
  },
  {
    id: 'a5',
    name: 'Elena Rocha',
    email: 'elena@emp.com',
    team_id: 't2',
    avatar: '',
    status: 'active',
    role: 'lead',
    total_conversations: 220,
    conversion_rate: 30.8,
    avg_response_time: 42,
    satisfaction_score: 4.6,
    created: '',
    updated: '',
    expand: { team_id: { id: 't2', name: 'Suporte Premium' } },
  },
  {
    id: 'a6',
    name: 'Felipe Alves',
    email: 'felipe@emp.com',
    team_id: 't2',
    avatar: '',
    status: 'active',
    role: 'agent',
    total_conversations: 134,
    conversion_rate: 18.5,
    avg_response_time: 75,
    satisfaction_score: 4.0,
    created: '',
    updated: '',
    expand: { team_id: { id: 't2', name: 'Suporte Premium' } },
  },
  {
    id: 'a7',
    name: 'Gabriel Lima',
    email: 'gabriel@emp.com',
    team_id: 't3',
    avatar: '',
    status: 'active',
    role: 'lead',
    total_conversations: 167,
    conversion_rate: 41.2,
    avg_response_time: 35,
    satisfaction_score: 4.9,
    created: '',
    updated: '',
    expand: { team_id: { id: 't3', name: 'Corporativo' } },
  },
  {
    id: 'a8',
    name: 'Helena Dias',
    email: 'helena@emp.com',
    team_id: 't3',
    avatar: '',
    status: 'active',
    role: 'agent',
    total_conversations: 143,
    conversion_rate: 26.7,
    avg_response_time: 58,
    satisfaction_score: 4.3,
    created: '',
    updated: '',
    expand: { team_id: { id: 't3', name: 'Corporativo' } },
  },
]

export const getAgents = async (): Promise<Agent[]> => {
  try {
    return (await pb
      .collection('agents')
      .getFullList({ expand: 'team_id', sort: '-created' })) as unknown as Agent[]
  } catch {
    return mockAgents
  }
}
